name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  loop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scripts: [lint, check]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v4
        with:
          path: node_modules
          key: pnpm-deps-${{ hashFiles('node_modules/.pnpm/lock.yaml') }}
          restore-keys: pnpm-deps-

      - name: Install Dependencies
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: "pnpm install"

      - run: "pnpm run ${{ matrix.scripts}}"
