name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  loop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scripts: [lint, check]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: node_modules
          key: bun-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/bun.lockb')) }}

      - name: Install Dependencies
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: "bun install"

      - run: "bun run ${{ matrix.scripts}}"
